Select Top 20 *
from customer_shopping_behavior;


--Q1. What is the total revenue generated by male vs. female customers?
Select 
	Gender,
	SUM("Purchase Amount (USD)") AS Revenue
From
	customer_shopping_behavior
Group by
	Gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
Select 
	[Customer ID],
	[Purchase Amount (USD)]
From 
	customer_shopping_behavior
Where 
   [Discount Applied] = 'Yes'
   And 
   [Purchase Amount (USD)] > (Select AVG([Purchase Amount (USD)]) From customer_shopping_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
Select Top 5 
	[Item Purchased],
	ROUND(AVG([Review Rating]),2) AS [Average Product Rating]
From 
	customer_shopping_behavior
Group By 
	[Item Purchased]
order by
	AVG([Review Rating]) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    [Shipping Type],
    ROUND(AVG([Purchase Amount (USD)]), 2) AS [Average Purchase Amount]
FROM 
    customer_shopping_behavior
WHERE
    [Shipping Type] IN ('Standard', 'Express')
GROUP BY 
    [Shipping Type];

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
Select 
	[Subscription Status],
	Count([Customer ID]) AS [Total Customer],
	ROUND(AVG([Purchase Amount (USD)]), 2) AS [Average Spend],
	ROUND(SUM([Purchase Amount (USD)]), 2) AS [Total Revenue]
From
	customer_shopping_behavior
Group By
	[Subscription Status]
Order By 
	[Total Revenue] DESC,
	[Average Spend] DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select Top 5 
	[Item Purchased],
	ROUND(100.0 * SUM(CASE WHEN [Discount Applied] = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
From 
	customer_shopping_behavior
Group By
	[Item Purchased]
ORDER BY 
	discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH customer_type AS (
	Select 
		[Customer ID],
		[Previous Purchases],
		CASE
			WHEN [Previous Purchases] = 0  Then 'New'
			When [Previous Purchases] between 1 And 10 Then 'Returning'
			Else 'Loyal'
		End AS customer_segment
	From
	customer_shopping_behavior
)
Select 
	customer_segment,
	COUNT([Customer ID]) AS Total_customers
From
	customer_type
Group By 
	customer_segment
Order By 
	Total_customers DESC;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
	Select
		[Category],
		[Item Purchased],
		Count([Customer ID]) AS total_orders,
		ROW_NUMBER() over(
			PARTITION BY [Category]
			Order By Count ([Customer ID]) DESC
		)AS item_rank
	From
		customer_shopping_behavior
	Group by
		[Category], [Item Purchased]
)
Select 
	item_rank,
	[Category],
	[Item Purchased],
	total_orders
From 
	item_counts
Where
	item_rank <= 3; 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select
	[Subscription Status],
	COUNT([Customer ID]) AS repeat_buyers
From
	customer_shopping_behavior
where
	[Previous Purchases] > 5
Group By
	[Subscription Status];

--Q10. What is the revenue contribution of each age group? 
SELECT 
    CASE 
        WHEN [Age] BETWEEN 18 AND 30 THEN '18-30 (Youth)'
        WHEN [Age] BETWEEN 31 AND 50 THEN '31-50 (Adults)'
        ELSE '51+ (Seniors)'
    END AS age_group,
    SUM([Purchase Amount (USD)]) AS total_revenue
FROM 
    customer_shopping_behavior
GROUP BY 
    CASE 
        WHEN [Age] BETWEEN 18 AND 30 THEN '18-30 (Youth)'
        WHEN [Age] BETWEEN 31 AND 50 THEN '31-50 (Adults)'
        ELSE '51+ (Seniors)'
    END
ORDER BY 
    total_revenue DESC;